// AUTO-GENERATED by tools/themes-fetch.sh — do not edit by hand.
// Source: https://github.com/storm119/Tilix-Themes
// Commit: 9a60818b8cb43d973e78567e7a47fe4d3bdbc3e3
// Themes: 64 (sorted by name, ANSI 16-colour palette)
// See relay/lib/THEMES_NOTICE for attribution and the bundle checksum.

window.TPThemes = {
  DEFAULT_DARK_ID: "one-dark",
  DEFAULT_LIGHT_ID: "github",
  THEMES: [
  {
    id: "3024-day",
    name: "3024 Day",
    fg: "#4a4543", bg: "#f7f7f7", isLight: true,
    palette: ["#090300", "#db2d20", "#01a252", "#fded02", "#01a0e4", "#a16a94", "#b5e4f4", "#a5a2a2", "#5c5855", "#e8bbd0", "#3a3432", "#4a4543", "#807d7c", "#d6d5d4", "#cdab53", "#f7f7f7"],
    comment: "Ported for Terminix Scheme"
  },
  {
    id: "3024-night",
    name: "3024 Night",
    fg: "#a5a2a2", bg: "#090300", isLight: false,
    palette: ["#090300", "#db2d20", "#01a252", "#fded02", "#01a0e4", "#a16a94", "#b5e4f4", "#a5a2a2", "#5c5855", "#e8bbd0", "#3a3432", "#4a4543", "#807d7c", "#d6d5d4", "#cdab53", "#f7f7f7"],
    comment: "Ported for Terminix Scheme"
  },
  {
    id: "adventuretime",
    name: "AdventureTime",
    fg: "#f8dcc0", bg: "#1f1d45", isLight: false,
    palette: ["#050404", "#bd0013", "#4ab118", "#e7741e", "#0f4ac6", "#665993", "#70a598", "#f8dcc0", "#4e7cbf", "#fc5f5a", "#9eff6e", "#efc11a", "#1997c6", "#9b5953", "#c8faf4", "#f6f5fb"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "afterglow",
    name: "Afterglow",
    fg: "#d0d0d0", bg: "#222222", isLight: false,
    palette: ["#151515", "#a53c23", "#7b9246", "#d3a04d", "#6c99bb", "#9f4e85", "#7dd6cf", "#d0d0d0", "#505050", "#a53c23", "#7b9246", "#d3a04d", "#547c99", "#9f4e85", "#7dd6cf", "#f5f5f5"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "alien-blood",
    name: "Alien Blood",
    fg: "#637d75", bg: "#0f1610", isLight: false,
    palette: ["#112616", "#7f2b27", "#2f7e25", "#717f24", "#2f6a7f", "#47587f", "#327f77", "#647d75", "#3c4812", "#e08009", "#18e000", "#bde000", "#00aae0", "#0058e0", "#00e0c4", "#73fa91"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "argonaut",
    name: "Argonaut",
    fg: "#fffaf4", bg: "#0e1019", isLight: false,
    palette: ["#232323", "#ff000f", "#8ce10b", "#ffb900", "#008df8", "#6d43a6", "#00d8eb", "#ffffff", "#444444", "#ff2740", "#abe15b", "#ffd242", "#0092ff", "#9a5feb", "#67fff0", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "arthur",
    name: "Arthur",
    fg: "#ddeedd", bg: "#1c1c1c", isLight: false,
    palette: ["#3d352a", "#cd5c5c", "#86af80", "#e8ae5b", "#6495ed", "#deb887", "#b0c4de", "#bbaa99", "#554444", "#cc5533", "#88aa22", "#ffa75d", "#87ceeb", "#996600", "#b0c4de", "#ddccbb"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "atom",
    name: "Atom",
    fg: "#c5c8c6", bg: "#161719", isLight: false,
    palette: ["#000000", "#fd5ff1", "#87c38a", "#ffd7b1", "#85befd", "#b9b6fc", "#85befd", "#e0e0e0", "#000000", "#fd5ff1", "#94fa36", "#f5ffa8", "#96cbfe", "#b9b6fc", "#85befd", "#e0e0e0"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "belafonte-day",
    name: "Belafonte Day",
    fg: "#45373c", bg: "#d5ccba", isLight: true,
    palette: ["#20111b", "#be100e", "#858162", "#eaa549", "#426a79", "#97522c", "#989a9c", "#968c83", "#5e5252", "#be100e", "#858162", "#eaa549", "#426a79", "#97522c", "#989a9c", "#d5ccba"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "belafonte-night",
    name: "Belafonte Night",
    fg: "#968c83", bg: "#20111b", isLight: false,
    palette: ["#20111b", "#be100e", "#858162", "#eaa549", "#426a79", "#97522c", "#989a9c", "#968c83", "#5e5252", "#be100e", "#858162", "#eaa549", "#426a79", "#97522c", "#989a9c", "#d5ccba"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "birdsofparadise",
    name: "BirdsOfParadise",
    fg: "#e0dbb7", bg: "#2a1f1d", isLight: false,
    palette: ["#573d26", "#be2d26", "#6ba18a", "#e99d2a", "#5a86ad", "#ac80a6", "#74a6ad", "#e0dbb7", "#9b6c4a", "#e84627", "#95d8ba", "#d0d150", "#b8d3ed", "#d19ecb", "#93cfd7", "#fff9d5"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "blazer",
    name: "Blazer",
    fg: "#d9e6f2", bg: "#0d1926", isLight: false,
    palette: ["#000000", "#b87a7a", "#7ab87a", "#b8b87a", "#7a7ab8", "#b87ab8", "#7ab8b8", "#d9d9d9", "#262626", "#dbbdbd", "#bddbbd", "#dbdbbd", "#bdbddb", "#dbbddb", "#bddbdb", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "borland",
    name: "Borland",
    fg: "#ffff4e", bg: "#0000a4", isLight: false,
    palette: ["#4f4f4f", "#ff6c60", "#a8ff60", "#ffffb6", "#96cbfe", "#ff73fd", "#c6c5fe", "#eeeeee", "#7c7c7c", "#ffb6b0", "#ceffac", "#ffffcc", "#b5dcff", "#ff9cfe", "#dfdffe", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "broadcast",
    name: "Broadcast",
    fg: "#e6e1dc", bg: "#2b2b2b", isLight: false,
    palette: ["#000000", "#da4939", "#519f50", "#ffd24a", "#6d9cbe", "#d0d0ff", "#6e9cbe", "#ffffff", "#323232", "#ff7b6b", "#83d182", "#ffff7c", "#9fcef0", "#ffffff", "#a0cef0", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "brogrammer",
    name: "Brogrammer",
    fg: "#d6dbe5", bg: "#131313", isLight: false,
    palette: ["#1f1f1f", "#f81118", "#2dc55e", "#ecba0f", "#2a84d2", "#4e5ab7", "#1081d6", "#d6dbe5", "#d6dbe5", "#de352e", "#1dd361", "#f3bd09", "#1081d6", "#5350b9", "#0f7ddb", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "c64",
    name: "C64",
    fg: "#7869c4", bg: "#40318d", isLight: false,
    palette: ["#090300", "#883932", "#55a049", "#bfce72", "#40318d", "#8b3f96", "#67b6bd", "#ffffff", "#000000", "#883932", "#55a049", "#bfce72", "#40318d", "#8b3f96", "#67b6bd", "#f7f7f7"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "chalk",
    name: "Chalk",
    fg: "#d2d8d9", bg: "#2b2d2e", isLight: false,
    palette: ["#7d8b8f", "#b23a52", "#789b6a", "#b9ac4a", "#2a7fac", "#bd4f5a", "#44a799", "#d2d8d9", "#888888", "#f24840", "#80c470", "#ffeb62", "#4196ff", "#fc5275", "#53cdbd", "#d2d8d9"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "chalkboard",
    name: "Chalkboard",
    fg: "#d9e6f2", bg: "#29262f", isLight: false,
    palette: ["#000000", "#c37372", "#72c373", "#c2c372", "#7372c3", "#c372c2", "#72c2c3", "#d9d9d9", "#323232", "#dbaaaa", "#aadbaa", "#dadbaa", "#aaaadb", "#dbaada", "#aadadb", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "ciapre",
    name: "Ciapre",
    fg: "#aea47a", bg: "#191c27", isLight: false,
    palette: ["#181818", "#810009", "#48513b", "#cc8b3f", "#576d8c", "#724d7c", "#5c4f4b", "#aea47f", "#555555", "#ac3835", "#a6a75d", "#dcdf7c", "#3097c6", "#d33061", "#f3dbb2", "#f4f4f4"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "clrs",
    name: "CLRS",
    fg: "#262626", bg: "#ffffff", isLight: true,
    palette: ["#000000", "#f8282a", "#328a5d", "#fa701d", "#135cd0", "#9f00bd", "#33c3c1", "#b3b3b3", "#555753", "#fb0416", "#2cc631", "#fdd727", "#1670ff", "#e900b0", "#3ad5ce", "#eeeeec"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "cobalt-neon",
    name: "Cobalt Neon",
    fg: "#8ff586", bg: "#142838", isLight: false,
    palette: ["#142631", "#ff2320", "#3ba5ff", "#e9e75c", "#8ff586", "#781aa0", "#8ff586", "#ba46b2", "#fff688", "#d4312e", "#8ff586", "#e9f06d", "#3c7dd2", "#8230a7", "#6cbc67", "#8ff586"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "cobalt2",
    name: "Cobalt2",
    fg: "#ffffff", bg: "#132738", isLight: false,
    palette: ["#000000", "#ff0000", "#38de21", "#ffe50a", "#1460d2", "#ff005d", "#00bbbb", "#bbbbbb", "#555555", "#f40e17", "#3bd01d", "#edc809", "#5555ff", "#ff55ff", "#6ae3fa", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "crayon-pony-fish",
    name: "Crayon Pony Fish",
    fg: "#68525a", bg: "#150707", isLight: false,
    palette: ["#2b1b1d", "#91002b", "#579524", "#ab311b", "#8c87b0", "#692f50", "#e8a866", "#68525a", "#3d2b2e", "#c5255d", "#8dff57", "#c8381d", "#cfc9ff", "#fc6cba", "#ffceaf", "#b0949d"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "dark-pastel",
    name: "Dark Pastel",
    fg: "#ffffff", bg: "#000000", isLight: false,
    palette: ["#000000", "#ff5555", "#55ff55", "#ffff55", "#5555ff", "#ff55ff", "#55ffff", "#bbbbbb", "#555555", "#ff5555", "#55ff55", "#ffff55", "#5555ff", "#ff55ff", "#55ffff", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "darkside",
    name: "Darkside",
    fg: "#bababa", bg: "#222324", isLight: false,
    palette: ["#000000", "#e8341c", "#68c256", "#f2d42c", "#1c98e8", "#8e69c9", "#1c98e8", "#bababa", "#000000", "#e05a4f", "#77b869", "#efd64b", "#387cd3", "#957bbe", "#3d97e2", "#bababa"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "desert",
    name: "Desert",
    fg: "#ffffff", bg: "#333333", isLight: false,
    palette: ["#4d4d4d", "#ff2b2b", "#98fb98", "#f0e68c", "#cd853f", "#ffdead", "#ffa0a0", "#f5deb3", "#555555", "#ff5555", "#55ff55", "#ffff55", "#87ceff", "#ff55ff", "#ffd700", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "dimmed-monokai",
    name: "Dimmed Monokai",
    fg: "#b9bcba", bg: "#1f1f1f", isLight: false,
    palette: ["#3a3d43", "#be3f48", "#879a3b", "#c5a635", "#4f76a1", "#855c8d", "#578fa4", "#b9bcba", "#888987", "#fb001f", "#0f722f", "#c47033", "#186de3", "#fb0067", "#2e706d", "#fdffb9"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "dracula",
    name: "Dracula",
    fg: "#f8f8f2", bg: "#1e1f29", isLight: false,
    palette: ["#000000", "#ff5555", "#50fa7b", "#f1fa8c", "#bd93f9", "#ff79c6", "#8be9fd", "#bbbbbb", "#555555", "#ff5555", "#50fa7b", "#f1fa8c", "#bd93f9", "#ff79c6", "#8be9fd", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "earthsong",
    name: "Earthsong",
    fg: "#e5c7a9", bg: "#292520", isLight: false,
    palette: ["#121418", "#c94234", "#85c54c", "#f5ae2e", "#1398b9", "#d0633d", "#509552", "#e5c6aa", "#675f54", "#ff645a", "#98e036", "#e0d561", "#5fdaff", "#ff9269", "#84f088", "#f6f7ec"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "elemental",
    name: "Elemental",
    fg: "#807a74", bg: "#22211d", isLight: false,
    palette: ["#3c3c30", "#98290f", "#479a43", "#7f7111", "#497f7d", "#7f4e2f", "#387f58", "#807974", "#555445", "#e0502a", "#61e070", "#d69927", "#79d9d9", "#cd7c54", "#59d599", "#fff1e9"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "espresso",
    name: "Espresso",
    fg: "#ffffff", bg: "#323232", isLight: false,
    palette: ["#353535", "#d25252", "#a5c261", "#ffc66d", "#6c99bb", "#d197d9", "#bed6ff", "#eeeeec", "#535353", "#f00c0c", "#c2e075", "#e1e48b", "#8ab7d9", "#efb5f7", "#dcf4ff", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "espresso-libre",
    name: "Espresso Libre",
    fg: "#b8a898", bg: "#2a211c", isLight: false,
    palette: ["#000000", "#cc0000", "#1a921c", "#f0e53a", "#0066ff", "#c5656b", "#06989a", "#d3d7cf", "#555753", "#ef2929", "#9aff87", "#fffb5c", "#43a8ed", "#ff818a", "#34e2e2", "#eeeeec"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "fishtank",
    name: "Fishtank",
    fg: "#ecf0fe", bg: "#232537", isLight: false,
    palette: ["#03073c", "#c6004a", "#acf157", "#fecd5e", "#525fb8", "#986f82", "#968763", "#ecf0fc", "#6c5b30", "#da4b8a", "#dbffa9", "#fee6a9", "#b2befa", "#fda5cd", "#a5bd86", "#f6ffec"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "flat",
    name: "Flat",
    fg: "#2cc55d", bg: "#002240", isLight: false,
    palette: ["#222d3f", "#a82320", "#32a548", "#e58d11", "#3167ac", "#781aa0", "#2c9370", "#b0b6ba", "#212c3c", "#d4312e", "#2d9440", "#e5be0c", "#3c7dd2", "#8230a7", "#35b387", "#e7eced"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "flatland",
    name: "Flatland",
    fg: "#b8dbef", bg: "#1d1f21", isLight: false,
    palette: ["#1d1d19", "#f18339", "#9fd364", "#f4ef6d", "#5096be", "#695abc", "#d63865", "#ffffff", "#1d1d19", "#d22a24", "#a7d42c", "#ff8949", "#61b9d0", "#695abc", "#d63865", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "flatty",
    name: "Flatty",
    fg: "#a1b0b8", bg: "#1f2c3a", isLight: false,
    palette: ["#2c3e50", "#c0392b", "#27ae5f", "#f39c11", "#2880b9", "#8e44ad", "#16a085", "#bdc3c7", "#33495e", "#e74b3b", "#2ecc71", "#f1c30f", "#3497db", "#9a59b6", "#29a198", "#eeeeec"],
    comment: "A simple original flat theme for Tilix"
  },
  {
    id: "frontend-delight",
    name: "Frontend Delight",
    fg: "#adadad", bg: "#1b1c1d", isLight: false,
    palette: ["#242526", "#f8511b", "#565747", "#fa771d", "#2c70b7", "#f02e4f", "#3ca1a6", "#adadad", "#5fac6d", "#f74319", "#74ec4c", "#fdc325", "#3393ca", "#e75e4f", "#4fbce6", "#8c735b"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "frontend-fun-forrest",
    name: "Frontend Fun Forrest",
    fg: "#dec165", bg: "#251200", isLight: false,
    palette: ["#000000", "#d6262b", "#919c00", "#be8a13", "#4699a3", "#8d4331", "#da8213", "#ddc265", "#7f6a55", "#e55a1c", "#bfc65a", "#ffcb1b", "#7cc9cf", "#d26349", "#e6a96b", "#ffeaa3"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "frontend-galaxy",
    name: "Frontend Galaxy",
    fg: "#ffffff", bg: "#1d2837", isLight: false,
    palette: ["#000000", "#f9555f", "#21b089", "#fef02a", "#589df6", "#944d95", "#1f9ee7", "#bbbbbb", "#555555", "#fa8c8f", "#35bb9a", "#ffff55", "#589df6", "#e75699", "#3979bc", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "github",
    name: "Github",
    fg: "#3e3e3e", bg: "#f4f4f4", isLight: true,
    palette: ["#3e3e3e", "#970b16", "#07962a", "#f8eec7", "#003e8a", "#e94691", "#89d1ec", "#ffffff", "#666666", "#de0000", "#87d5a2", "#f1d007", "#2e6cba", "#ffa29f", "#1cfafe", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "grape",
    name: "Grape",
    fg: "#9f9fa1", bg: "#171423", isLight: false,
    palette: ["#2d283f", "#ed2261", "#1fa91b", "#8ddc20", "#487df4", "#8d35c9", "#3bdeed", "#9e9ea0", "#59516a", "#f0729a", "#53aa5e", "#b2dc87", "#a9bcec", "#ad81c2", "#9de3eb", "#a288f7"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "grass",
    name: "Grass",
    fg: "#fff0a5", bg: "#13773d", isLight: false,
    palette: ["#000000", "#bb0000", "#00bb00", "#e7b000", "#0000a3", "#950062", "#00bbbb", "#bbbbbb", "#555555", "#bb0000", "#00bb00", "#e7b000", "#0000bb", "#ff55ff", "#55ffff", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "gruvbox-for-tilix",
    name: "Gruvbox for Tilix",
    fg: "#ebdbb2", bg: "#282828", isLight: false,
    palette: ["#282828", "#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#a89984", "#928374", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#ebdbb2"],
    comment: "Ported for Trilix Colour Scheme"
  },
  {
    id: "hardcore",
    name: "Hardcore",
    fg: "#a0a0a0", bg: "#121212", isLight: false,
    palette: ["#1b1d1e", "#f92672", "#a6e22e", "#fd971f", "#66d9ef", "#9e6ffe", "#5e7175", "#ccccc6", "#505354", "#ff669d", "#beed5f", "#e6db74", "#66d9ef", "#9e6ffe", "#a3babf", "#f8f8f2"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "harper",
    name: "Harper",
    fg: "#a8a49d", bg: "#010101", isLight: false,
    palette: ["#010101", "#f8b63f", "#7fb5e1", "#d6da25", "#489e48", "#b296c6", "#f5bfd7", "#a8a49d", "#726e6a", "#f8b63f", "#7fb5e1", "#d6da25", "#489e48", "#b296c6", "#f5bfd7", "#fefbea"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "highway",
    name: "Highway",
    fg: "#ededed", bg: "#222225", isLight: false,
    palette: ["#000000", "#d00e18", "#138034", "#ffcb3e", "#006bb3", "#6b2775", "#384564", "#ededed", "#5d504a", "#f07e18", "#b1d130", "#fff120", "#4fc2fd", "#de0071", "#5d504a", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "hipster-green",
    name: "Hipster Green",
    fg: "#84c138", bg: "#100b05", isLight: false,
    palette: ["#000000", "#b6214a", "#00a600", "#bfbf00", "#246eb2", "#b200b2", "#00a6b2", "#bfbfbf", "#666666", "#e50000", "#86a93e", "#e5e500", "#0000ff", "#e500e5", "#00e5e5", "#e5e5e5"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "homebrew",
    name: "Homebrew",
    fg: "#00ff00", bg: "#000000", isLight: false,
    palette: ["#000000", "#990000", "#00a600", "#999900", "#0000b2", "#b200b2", "#00a6b2", "#bfbfbf", "#666666", "#e50000", "#00d900", "#e5e500", "#0000ff", "#e500e5", "#00e5e5", "#e5e5e5"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "hurtado",
    name: "Hurtado",
    fg: "#dbdbdb", bg: "#000000", isLight: false,
    palette: ["#575757", "#ff1b00", "#a5e055", "#fbe74a", "#496487", "#fd5ff1", "#86e9fe", "#cbcccb", "#262626", "#d51d00", "#a5df55", "#fbe84a", "#89beff", "#c001c1", "#86eafe", "#dbdbdb"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "hybrid",
    name: "Hybrid",
    fg: "#b7bcba", bg: "#161719", isLight: false,
    palette: ["#2a2e33", "#b84d51", "#b3bf5a", "#e4b55e", "#6e90b0", "#a17eac", "#7fbfb4", "#b5b9b6", "#1d1f22", "#8d2e32", "#798431", "#e58a50", "#4b6b88", "#6e5079", "#4d7b74", "#5a626a"],
    comment: "Based on w0ng-Hybrid Ported for Terminix Colour Scheme"
  },
  {
    id: "ic-green-ppl",
    name: "IC Green PPL",
    fg: "#d9efd3", bg: "#3a3d3f", isLight: false,
    palette: ["#1f1f1f", "#fb002a", "#339c24", "#659b25", "#149b45", "#53b82c", "#2cb868", "#e0ffef", "#032710", "#a7ff3f", "#9fff6d", "#d2ff6d", "#72ffb5", "#50ff3e", "#22ff71", "#daefd0"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "ic-orange-ppl",
    name: "IC Orange PPL",
    fg: "#ffcb83", bg: "#262626", isLight: false,
    palette: ["#000000", "#c13900", "#a4a900", "#caaf00", "#bd6d00", "#fc5e00", "#f79500", "#ffc88a", "#6a4f2a", "#ff8c68", "#f6ff40", "#ffe36e", "#ffbe55", "#fc874f", "#c69752", "#fafaff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "idle-toes",
    name: "Idle Toes",
    fg: "#ffffff", bg: "#323232", isLight: false,
    palette: ["#323232", "#d25252", "#7fe173", "#ffc66d", "#4099ff", "#f680ff", "#bed6ff", "#eeeeec", "#535353", "#f07070", "#9dff91", "#ffe48b", "#5eb7f7", "#ff9dff", "#dcf4ff", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "ir-black",
    name: "IR Black",
    fg: "#f1f1f1", bg: "#000000", isLight: false,
    palette: ["#4f4f4f", "#fa6c60", "#a8ff60", "#fffeb7", "#96cafe", "#fa73fd", "#c6c5fe", "#efedef", "#7b7b7b", "#fcb6b0", "#cfffab", "#ffffcc", "#b5dcff", "#fb9cfe", "#e0e0fe", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "jackie-brown",
    name: "Jackie Brown",
    fg: "#ffcc2f", bg: "#2c1d16", isLight: false,
    palette: ["#2c1d16", "#ef5734", "#2baf2b", "#bebf00", "#246eb2", "#d05ec1", "#00acee", "#bfbfbf", "#666666", "#e50000", "#86a93e", "#e5e500", "#0000ff", "#e500e5", "#00e5e5", "#e5e5e5"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "japanesque",
    name: "Japanesque",
    fg: "#f7f6ec", bg: "#1e1e1e", isLight: false,
    palette: ["#343935", "#cf3f61", "#7bb75b", "#e9b32a", "#4c9ad4", "#a57fc4", "#389aad", "#fafaf6", "#595b59", "#d18fa6", "#767f2c", "#78592f", "#135979", "#604291", "#76bbca", "#b2b5ae"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "jellybeans",
    name: "Jellybeans",
    fg: "#dedede", bg: "#121212", isLight: false,
    palette: ["#929292", "#e27373", "#94b979", "#ffba7b", "#97bedc", "#e1c0fa", "#00988e", "#dedede", "#bdbdbd", "#ffa1a1", "#bddeab", "#ffdca0", "#b1d8f6", "#fbdaff", "#1ab2a8", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "kibble",
    name: "Kibble",
    fg: "#f7f7f7", bg: "#0e100a", isLight: false,
    palette: ["#4d4d4d", "#c70031", "#29cf13", "#d8e30e", "#3449d1", "#8400ff", "#0798ab", "#e2d1e3", "#5a5a5a", "#f01578", "#6ce05c", "#f3f79e", "#97a4f7", "#c495f0", "#68f2e0", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "later-this-evening",
    name: "Later This Evening",
    fg: "#959595", bg: "#222222", isLight: false,
    palette: ["#2b2b2b", "#d45a60", "#afba67", "#e5d289", "#a0bad6", "#c092d6", "#91bfb7", "#3c3d3d", "#454747", "#d3232f", "#aabb39", "#e5be39", "#6699d6", "#ab53d6", "#5fc0ae", "#c1c2c2"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "lavandula",
    name: "Lavandula",
    fg: "#736e7d", bg: "#050014", isLight: false,
    palette: ["#230046", "#7d1625", "#337e6f", "#7f6f49", "#4f4a7f", "#5a3f7f", "#58777f", "#736e7d", "#372d46", "#e05167", "#52e0c4", "#e0c386", "#8e87e0", "#a776e0", "#9ad4e0", "#8c91fa"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "liquid-carbon",
    name: "Liquid Carbon",
    fg: "#afc2c2", bg: "#303030", isLight: false,
    palette: ["#000000", "#ff3030", "#559a70", "#ccac00", "#0099cc", "#cc69c8", "#7ac4cc", "#bccccc", "#000000", "#ff3030", "#559a70", "#ccac00", "#0099cc", "#cc69c8", "#7ac4cc", "#bccccc"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "liquid-carbon-transparent",
    name: "Liquid Carbon Transparent",
    fg: "#afc2c2", bg: "#000000", isLight: false,
    palette: ["#000000", "#ff3030", "#559a70", "#ccac00", "#0099cc", "#cc69c8", "#7ac4cc", "#bccccc", "#000000", "#ff3030", "#559a70", "#ccac00", "#0099cc", "#cc69c8", "#7ac4cc", "#bccccc"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "one-dark",
    name: "One Dark",
    fg: "#abb2bf", bg: "#282c34", isLight: false,
    palette: ["#000000", "#e06c75", "#98c379", "#d19a66", "#61aeee", "#c678dd", "#56b6c2", "#abb2bf", "#5c6370", "#e06c75", "#98c379", "#d19a66", "#62afee", "#c678dd", "#56b6c2", "#ffffff"],
    comment: "Ported for Terminix Colour Scheme"
  },
  {
    id: "terminix-dark",
    name: "Terminix Dark",
    fg: "#868a8c", bg: "#091116", isLight: false,
    palette: ["#282a2e", "#a54242", "#a1b56c", "#de935f", "#225555", "#85678f", "#5e8d87", "#777777", "#373b41", "#c63535", "#608360", "#fa805a", "#449da1", "#ba8baf", "#86c1b9", "#c5c8c6"],
    comment: "Created by storm119 for Terminix Colour Scheme"
  }
  ]
};
