#!/usr/bin/env bash
# Installs the `termpilot` shell function (and, when free, a short `tp`
# alias) pointing at THIS checkout of termpilot. Idempotent: re-run from
# any checkout to repoint.
#
# Works on Linux and macOS. Both bash and zsh users get a fenced
# source-line block in their respective rc files.
#
# What it does:
#   1) Captures the directory containing this install.sh.
#   2) Writes a function definition to ~/.config/termpilot/termpilot.sh
#      (overwritten on every run — this is the source of truth for `termpilot`).
#      The same file also defines an `alias tp=termpilot` if nothing
#      else on this system already claims the name `tp`. The check is
#      re-evaluated on every shell start, so a later install of a tool
#      named `tp` (e.g. from apt) will silently disable the shortcut.
#   3) Adds a fenced source-line block to every shell rc file that exists
#      or matches the user's $SHELL (~/.bashrc, ~/.bash_profile on macOS,
#      ~/.zshrc).
#
# After running:  open a new terminal (or source the rc file), then:
#   termpilot --set-relay-url https://your.host/path
#   termpilot --generate-token
# and you're ready to go.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRAP_PATH="$SCRIPT_DIR/termpilot-wrap"
UNINSTALL_PATH="$SCRIPT_DIR/uninstall.sh"
CONFIG_DIR="$HOME/.config/termpilot"
RELAY_URL_FILE="$CONFIG_DIR/relay-url"
SECRET_FILE="$CONFIG_DIR/relay-secret"
ALIAS_FILE="$CONFIG_DIR/termpilot.sh"
TAG_OPEN="# >>> termpilot >>>"
TAG_CLOSE="# <<< termpilot <<<"

# date -Is is GNU-only; macOS BSD date wants +%FT%T%z.
if NOW_ISO="$(date -Is 2>/dev/null)"; then :; else NOW_ISO="$(date +%FT%T%z)"; fi

# --- Sanity checks ---------------------------------------------------------

if [[ ! -f "$WRAP_PATH" ]]; then
    echo "error: termpilot-wrap not found at $WRAP_PATH" >&2
    echo "       (this script must live next to termpilot-wrap)" >&2
    exit 1
fi
[[ -x "$WRAP_PATH" ]] || chmod +x "$WRAP_PATH"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

# --- Write the function file (always overwritten) -------------------------

cat > "$ALIAS_FILE" <<EOF
# Auto-generated by $SCRIPT_DIR/install.sh on $NOW_ISO
# Re-run install.sh from any termpilot checkout to repoint termpilot there.
# Source: $SCRIPT_DIR
#
# Subcommands:
#   termpilot --help                       show usage
#   termpilot --set-relay-url URL          persist the relay URL
#   termpilot --get-relay-url              print the configured relay URL
#   termpilot --set-relay-secret SECRET   persist the relay Bearer token
#   termpilot --clear-relay-secret        forget the relay Bearer token
#   termpilot --generate-token             create or replace the encryption token
#   termpilot --show-token                 reveal the stored token (after password)
#   termpilot --uninstall                  remove termpilot from this machine
#   termpilot                              spawn \$SHELL through the wrapper
#   termpilot bash                         spawn bash explicitly
#   termpilot tmux new -A -s main          attach/create persistent tmux session
#   termpilot htop                         run any program in a PTY

termpilot() {
    if [[ ! -x "$WRAP_PATH" ]]; then
        echo "termpilot: $WRAP_PATH is missing or not executable — re-run install.sh" >&2
        return 1
    fi
    case "\${1:-}" in
        --uninstall|uninstall)
            # Route to the sibling uninstall.sh. From a dev-mode shim the
            # script lives in the checkout and will refuse via its .git
            # guard, telling the user to use the deployed copy.
            if [[ ! -x "$UNINSTALL_PATH" ]]; then
                echo "termpilot: $UNINSTALL_PATH is missing or not executable" >&2
                return 1
            fi
            shift
            "$UNINSTALL_PATH" "\$@"
            return
            ;;
        --help|-h|help|\\
        --generate-token|generate-token|\\
        --show-token|show-token|\\
        --set-relay-url|set-relay-url|\\
        --get-relay-url|get-relay-url|\\
        --set-relay-secret|set-relay-secret|\\
        --clear-relay-secret|clear-relay-secret|\\
        --version|version|-V|\\
        --update|update|\\
        --test-connection|test-connection|\\
        --activate-mcp|activate-mcp|\\
        --deactivate-mcp|deactivate-mcp|\\
        ls|tail|screenshot|transcript|gc|send|wait|mcp-serve)
            "$WRAP_PATH" "\$@"
            return
            ;;
    esac
    local tp_relay=""
    if [[ -r "$RELAY_URL_FILE" ]]; then
        tp_relay="\$(cat "$RELAY_URL_FILE")"
    fi
    if [[ -z "\$tp_relay" ]]; then
        echo "termpilot: relay URL not configured." >&2
        echo "  Run: termpilot --set-relay-url https://your.host/path" >&2
        return 2
    fi
    local tp_secret=""
    if [[ -r "$SECRET_FILE" ]]; then
        tp_secret="\$(cat "$SECRET_FILE")"
    fi
    # If the user passed no command, default to \$SHELL (fallback /bin/bash).
    # Wrapper flags (--force, --insecure, ...) are parsed by argparse from
    # anywhere in argv, so the user can mix them in freely.
    local default_shell="\${SHELL:-/bin/bash}"
    if [[ \$# -eq 0 ]]; then
        TERMPILOT_RELAY="\$tp_relay" TERMPILOT_SECRET="\$tp_secret" \\
            "$WRAP_PATH" run --title "\$(basename "\$PWD")" -- "\$default_shell"
    else
        TERMPILOT_RELAY="\$tp_relay" TERMPILOT_SECRET="\$tp_secret" \\
            "$WRAP_PATH" run --title "\$(basename "\$PWD")" "\$@"
    fi
}

# Short alias 'tp' — only defined if nothing else on this system already
# claims that name. Re-evaluated on every shell start, so installing a
# tool that provides 'tp' later (e.g. via apt) will silently disable
# this shortcut without you having to rerun install.sh.
if ! command -v tp >/dev/null 2>&1; then
    alias tp=termpilot
fi
EOF

# Append the bash completion in a single-quoted heredoc so we don't have to
# escape every $ in the function body. Sources alongside the function above,
# so users get `termpilot --h<Tab>` → `termpilot --help` without extra setup.
cat >> "$ALIAS_FILE" <<'EOF'

# --- Tab completion (bash + zsh) -----------------------------------------
# Same function body works in zsh once `bashcompinit` is loaded. The zsh
# branch silently no-ops if the user's setup doesn't have `compinit`
# loaded (rare — Oh-My-Zsh, Prezto, and most manual configs load it).
_termpilot_complete() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]:-}"

    # Refuse to complete after flags whose argument is a secret or
    # free-form value — completing a secret to a filename would be
    # confusing at best, leaky at worst.
    case "$prev" in
        --set-relay-secret|set-relay-secret|--auth)
            return 0 ;;
        --set-relay-url|set-relay-url|--relay|--title|--instance)
            return 0 ;;
    esac

    # Top-level verbs (mutually-exclusive with running a program).
    local verbs="--help -h help
        --version version -V
        --update update
        --uninstall uninstall
        --test-connection test-connection
        --generate-token generate-token
        --show-token show-token
        --set-relay-url set-relay-url
        --get-relay-url get-relay-url
        --set-relay-secret set-relay-secret
        --clear-relay-secret clear-relay-secret
        --activate-mcp activate-mcp
        --deactivate-mcp deactivate-mcp
        ls tail screenshot transcript gc send wait mcp-serve"
    # Flags that ride alongside the program being wrapped.
    local run_flags="--title --no-local --no-local-input --insecure --force --instance --relay --auth"

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$verbs $run_flags" -- "$cur") )
        return 0
    fi

    # First positional: offer verbs plus anything on $PATH, so
    # `termpilot tm<Tab>` → `termpilot tmux` works.
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$verbs" -- "$cur") )
        COMPREPLY+=( $(compgen -c -- "$cur") )
        return 0
    fi

    # Past the first arg: file/dir completion is the most useful default.
    COMPREPLY=( $(compgen -f -- "$cur") )
    return 0
}

if [[ -n "${BASH_VERSION:-}" ]]; then
    complete -F _termpilot_complete termpilot
    # Only attach to `tp` if it's still pointing at us — don't hijack the
    # completion of whatever tool installed a `tp` of its own.
    if alias tp 2>/dev/null | grep -q '=.termpilot.'; then
        complete -F _termpilot_complete tp
    fi
elif [[ -n "${ZSH_VERSION:-}" ]]; then
    # `complete -F` is a bash builtin; bashcompinit ports it into zsh.
    # Errors silenced so users without compinit don't see noise on startup.
    if autoload -U +X bashcompinit 2>/dev/null && bashcompinit 2>/dev/null; then
        complete -F _termpilot_complete termpilot 2>/dev/null
        if alias tp 2>/dev/null | grep -q '=.termpilot.'; then
            complete -F _termpilot_complete tp 2>/dev/null
        fi
    fi
fi
EOF

# --- Fish: function + completion (only when fish is present) --------------
# Fish doesn't read .bashrc / .zshrc, and bash function syntax doesn't
# parse there. We ship a parallel fish function and a native fish
# completion file, both auto-loaded by fish.
FISH_FN=""
FISH_COMP=""
if command -v fish >/dev/null 2>&1 || [[ -d "$HOME/.config/fish" ]]; then
    FISH_FN="$HOME/.config/fish/functions/termpilot.fish"
    FISH_COMP="$HOME/.config/fish/completions/termpilot.fish"
    mkdir -p "$(dirname "$FISH_FN")" "$(dirname "$FISH_COMP")"

    # Function — mirrors the bash version's logic but in fish syntax.
    cat > "$FISH_FN" <<EOF
# Auto-generated by $SCRIPT_DIR/install.sh on $NOW_ISO
# Re-run install.sh from any termpilot checkout to repoint termpilot there.
# Source: $SCRIPT_DIR
function termpilot --description 'TermPilot session wrapper'
    set -l wrap "$WRAP_PATH"
    set -l uninstaller "$UNINSTALL_PATH"
    if not test -x "\$wrap"
        echo "termpilot: \$wrap is missing or not executable — re-run install.sh" >&2
        return 1
    end
    switch "\$argv[1]"
        case --uninstall uninstall
            if not test -x "\$uninstaller"
                echo "termpilot: \$uninstaller is missing or not executable" >&2
                return 1
            end
            "\$uninstaller" \$argv[2..-1]
            return \$status
        case --help -h help \\
             --generate-token generate-token \\
             --show-token show-token \\
             --set-relay-url set-relay-url \\
             --get-relay-url get-relay-url \\
             --set-relay-secret set-relay-secret \\
             --clear-relay-secret clear-relay-secret \\
             --version version -V \\
             --update update \\
             --test-connection test-connection \\
             --activate-mcp activate-mcp \\
             --deactivate-mcp deactivate-mcp \\
             ls tail screenshot transcript gc send wait mcp-serve
            "\$wrap" \$argv
            return \$status
    end
    set -l tp_relay ""
    if test -r "$RELAY_URL_FILE"
        set tp_relay (cat "$RELAY_URL_FILE")
    end
    if test -z "\$tp_relay"
        echo "termpilot: relay URL not configured." >&2
        echo "  Run: termpilot --set-relay-url https://your.host/path" >&2
        return 2
    end
    set -l tp_secret ""
    if test -r "$SECRET_FILE"
        set tp_secret (cat "$SECRET_FILE")
    end
    set -l default_shell "\$SHELL"
    test -z "\$default_shell"; and set default_shell /bin/bash
    set -lx TERMPILOT_RELAY "\$tp_relay"
    set -lx TERMPILOT_SECRET "\$tp_secret"
    if test (count \$argv) -eq 0
        "\$wrap" run --title (basename "\$PWD") -- "\$default_shell"
    else
        "\$wrap" run --title (basename "\$PWD") \$argv
    end
end

# Short alias 'tp' — only when nothing else claims it.
if not type -q tp
    alias tp=termpilot
    funcsave tp >/dev/null 2>&1
end
EOF

    # Completion — fish's native DSL. No need for the heredoc to expand.
    cat > "$FISH_COMP" <<'EOF'
# Auto-generated by install.sh. Re-run install.sh to refresh.
# Disable file completion by default; individual rules re-enable it
# where appropriate (e.g. the program-to-run argument).
complete -c termpilot -f

complete -c termpilot -l help            -d 'Show usage'
complete -c termpilot -l version         -d 'Show version'
complete -c termpilot -l update          -d 'Re-download bundled wrapper'
complete -c termpilot -l uninstall       -d 'Remove termpilot from this machine'
complete -c termpilot -l test-connection -d 'Probe relay reachability'
complete -c termpilot -l generate-token  -d 'Create/replace the encryption token'
complete -c termpilot -l show-token      -d 'Reveal the stored token (after sudo)'
complete -c termpilot -l set-relay-url   -d 'Persist the relay URL'           -r
complete -c termpilot -l get-relay-url   -d 'Print the configured relay URL'
complete -c termpilot -l set-relay-secret   -d 'Persist the relay Bearer token' -r
complete -c termpilot -l clear-relay-secret -d 'Forget the relay Bearer token'
complete -c termpilot -l activate-mcp       -d 'Install MCP server + register with Claude Code'
complete -c termpilot -l deactivate-mcp     -d 'Unregister MCP server from Claude Code'

complete -c termpilot -l title    -d 'Session title' -r
complete -c termpilot -l no-local -d "Don't echo to local terminal"
complete -c termpilot -l no-local-input -d "Don't read sibling-process input from in.local"
complete -c termpilot -l insecure -d 'Allow self-signed relay cert'
complete -c termpilot -l force    -d 'Override another wrapper holding the cwd lock'
complete -c termpilot -l instance -d 'Override auto-derived instance name' -r
complete -c termpilot -l relay    -d 'Override TERMPILOT_RELAY for this run' -r
complete -c termpilot -l auth     -d 'Override TERMPILOT_SECRET for this run' -r

# Verb forms without leading --.
complete -c termpilot -n '__fish_is_first_token' -a help               -d 'Show usage'
complete -c termpilot -n '__fish_is_first_token' -a version            -d 'Show version'
complete -c termpilot -n '__fish_is_first_token' -a update             -d 'Re-download bundled wrapper'
complete -c termpilot -n '__fish_is_first_token' -a uninstall          -d 'Remove termpilot from this machine'
complete -c termpilot -n '__fish_is_first_token' -a test-connection    -d 'Probe relay reachability'
complete -c termpilot -n '__fish_is_first_token' -a generate-token     -d 'Create/replace the encryption token'
complete -c termpilot -n '__fish_is_first_token' -a show-token         -d 'Reveal the stored token (after sudo)'
complete -c termpilot -n '__fish_is_first_token' -a set-relay-url      -d 'Persist the relay URL'
complete -c termpilot -n '__fish_is_first_token' -a get-relay-url      -d 'Print the configured relay URL'
complete -c termpilot -n '__fish_is_first_token' -a set-relay-secret   -d 'Persist the relay Bearer token'
complete -c termpilot -n '__fish_is_first_token' -a clear-relay-secret -d 'Forget the relay Bearer token'
complete -c termpilot -n '__fish_is_first_token' -a activate-mcp       -d 'Install + register MCP server'
complete -c termpilot -n '__fish_is_first_token' -a deactivate-mcp     -d 'Unregister MCP server'
complete -c termpilot -n '__fish_is_first_token' -a ls                 -d 'List local termpilot sessions'
complete -c termpilot -n '__fish_is_first_token' -a tail               -d 'Tail another session output'
complete -c termpilot -n '__fish_is_first_token' -a screenshot         -d 'Render another session screen via pyte'
complete -c termpilot -n '__fish_is_first_token' -a transcript         -d 'Dump full session history via pyte scrollback'
complete -c termpilot -n '__fish_is_first_token' -a gc                 -d 'Garbage-collect forgotten wrappers by age'
complete -c termpilot -n '__fish_is_first_token' -a send               -d 'Type into another session'
complete -c termpilot -n '__fish_is_first_token' -a wait               -d 'Block until session idle / regex match'
complete -c termpilot -n '__fish_is_first_token' -a mcp-serve          -d 'Run the stdio MCP server'

# First positional argument that doesn't match a verb: a program to run.
complete -c termpilot -n '__fish_is_first_token' -a '(__fish_complete_command)' -d 'Run program in PTY'
EOF
fi

# --- Idempotent source-block in shell rc files ---------------------------
# Pick rc files based on which shells the user actually uses. macOS users
# default to zsh (and login shells read ~/.bash_profile, not ~/.bashrc),
# so we cover all the common cases.

RC_FILES=()
case "${SHELL:-}" in
    */zsh)  RC_FILES+=("$HOME/.zshrc") ;;
    */bash) RC_FILES+=("$HOME/.bashrc") ;;
esac
# Also patch any rc files that already exist, even if they're not $SHELL
# — users often switch shells later or run termpilot from both.
for rc in "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.zshrc"; do
    if [[ -f "$rc" ]]; then
        already=0
        for x in "${RC_FILES[@]:-}"; do [[ "$x" == "$rc" ]] && already=1; done
        [[ $already -eq 0 ]] && RC_FILES+=("$rc")
    fi
done
# Fallback: if none of the above matched (fresh account, no rc files yet),
# create ~/.bashrc on Linux or ~/.zshrc on macOS so `termpilot` is at
# least defined somewhere.
if [[ ${#RC_FILES[@]} -eq 0 ]]; then
    case "$(uname -s 2>/dev/null)" in
        Darwin) RC_FILES+=("$HOME/.zshrc") ;;
        *)      RC_FILES+=("$HOME/.bashrc") ;;
    esac
fi

PATCHED_FILES=()
for rc in "${RC_FILES[@]}"; do
    touch "$rc"
    if grep -qF "$TAG_OPEN" "$rc"; then
        # Replace existing block in case the alias-file path ever changes.
        awk -v tag_open="$TAG_OPEN" -v tag_close="$TAG_CLOSE" -v alias_file="$ALIAS_FILE" '
            BEGIN { in_block = 0 }
            $0 == tag_open  { print tag_open; print "[ -f \"" alias_file "\" ] && source \"" alias_file "\""; print tag_close; in_block = 1; next }
            $0 == tag_close { in_block = 0; next }
            !in_block       { print }
        ' "$rc" > "$rc.tmp"
        mv "$rc.tmp" "$rc"
    else
        {
            printf '\n%s\n' "$TAG_OPEN"
            printf '[ -f "%s" ] && source "%s"\n' "$ALIAS_FILE" "$ALIAS_FILE"
            printf '%s\n' "$TAG_CLOSE"
        } >> "$rc"
    fi
    PATCHED_FILES+=("$rc")
done

# --- Reactivate MCP if previously activated -------------------------------
# Detection: a marker file at ~/.config/termpilot/mcp-active, written by
# `termpilot --activate-mcp` and removed by --deactivate-mcp. A fresh
# install never auto-activates (we don't want install.sh to talk to
# `claude` and write to the user's MCP config without prior opt-in).
# A re-install always reactivates: --activate-mcp rebuilds the venv from
# scratch and re-registers, so the new wrapper is paired with a matching
# `mcp` package version (no chance of skew from a stale venv).
#
# Legacy migration: pre-marker activations only left a venv behind.
# Stamp the marker if we see a venv but no marker, so users who
# activated under the old convention still get reactivated.

MCP_VENV="$HOME/.local/share/termpilot/mcp-venv"
MCP_ACTIVE_MARKER="$HOME/.config/termpilot/mcp-active"
if [[ ! -f "$MCP_ACTIVE_MARKER" && -x "$MCP_VENV/bin/python" ]]; then
    mkdir -p "$(dirname "$MCP_ACTIVE_MARKER")"
    date +%s > "$MCP_ACTIVE_MARKER"
fi

if [[ -f "$MCP_ACTIVE_MARKER" ]]; then
    echo
    echo "MCP previously activated; rebuilding venv against this install..."
    if "$WRAP_PATH" --activate-mcp; then
        echo "  ✓ MCP reactivated"
    else
        rc=$?
        echo "  ! MCP reactivation returned exit $rc (install continues)"
        echo "    Re-run manually with: termpilot --activate-mcp"
    fi
fi

# --- Report ---------------------------------------------------------------

echo "Installed."
echo "  function:     termpilot"
echo "  defined in:   $ALIAS_FILE"
echo "  binary:       $WRAP_PATH"
echo "  config dir:   $CONFIG_DIR"
echo "  rc files:     ${PATCHED_FILES[*]}"
if [[ -n "$FISH_FN" ]]; then
    echo "  fish func:    $FISH_FN"
    echo "  fish compl:   $FISH_COMP"
fi

# Report whether the 'tp' shortcut will activate on next shell start.
# The alias file does the real decision at runtime; this is just to
# inform the user up front.
if command -v tp >/dev/null 2>&1; then
    existing="$(type -p tp 2>/dev/null || true)"
    [[ -z "$existing" ]] && existing="$(type tp 2>&1 | head -1)"
    echo "  short alias:  tp NOT registered — '$existing' already claims that name"
else
    echo "  short alias:  tp  (also runs termpilot)"
fi
echo
echo "Activate now:  source ${PATCHED_FILES[0]}      (or open a new terminal)"
echo
echo "Next steps:"
if [[ ! -r "$RELAY_URL_FILE" ]]; then
    echo "  1. Tell termpilot where your relay lives:"
    echo "       termpilot --set-relay-url https://your.host/path"
fi
if [[ ! -r "$SECRET_FILE" ]]; then
    echo "  2. (Only if your relay sets RELAY_SECRET in config.php)"
    echo "       echo -n 'YOUR_RELAY_SECRET' > $SECRET_FILE && chmod 600 $SECRET_FILE"
fi
echo "  3. Generate your encryption token:"
echo "       termpilot --generate-token"
echo "  4. Paste the hex into the browser's manage-tokens dialog."
echo "  5. cd into a project and run:  termpilot"
