#!/usr/bin/env bash
# Installs the `termpilot` shell function (and, when free, a short `tp`
# alias) pointing at THIS checkout of termpilot. Idempotent: re-run from
# any checkout to repoint.
#
# Works on Linux and macOS. Both bash and zsh users get a fenced
# source-line block in their respective rc files.
#
# What it does:
#   1) Captures the directory containing this install.sh.
#   2) Writes a function definition to ~/.config/termpilot/termpilot.sh
#      (overwritten on every run — this is the source of truth for `termpilot`).
#      The same file also defines an `alias tp=termpilot` if nothing
#      else on this system already claims the name `tp`. The check is
#      re-evaluated on every shell start, so a later install of a tool
#      named `tp` (e.g. from apt) will silently disable the shortcut.
#   3) Adds a fenced source-line block to every shell rc file that exists
#      or matches the user's $SHELL (~/.bashrc, ~/.bash_profile on macOS,
#      ~/.zshrc).
#
# After running:  open a new terminal (or source the rc file), then:
#   termpilot --set-relay-url https://your.host/path
#   termpilot --generate-token
# and you're ready to go.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRAP_PATH="$SCRIPT_DIR/termpilot-wrap"
CONFIG_DIR="$HOME/.config/termpilot"
RELAY_URL_FILE="$CONFIG_DIR/relay-url"
SECRET_FILE="$CONFIG_DIR/relay-secret"
ALIAS_FILE="$CONFIG_DIR/termpilot.sh"
TAG_OPEN="# >>> termpilot >>>"
TAG_CLOSE="# <<< termpilot <<<"

# date -Is is GNU-only; macOS BSD date wants +%FT%T%z.
if NOW_ISO="$(date -Is 2>/dev/null)"; then :; else NOW_ISO="$(date +%FT%T%z)"; fi

# --- Sanity checks ---------------------------------------------------------

if [[ ! -f "$WRAP_PATH" ]]; then
    echo "error: termpilot-wrap not found at $WRAP_PATH" >&2
    echo "       (this script must live next to termpilot-wrap)" >&2
    exit 1
fi
[[ -x "$WRAP_PATH" ]] || chmod +x "$WRAP_PATH"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

# --- Write the function file (always overwritten) -------------------------

cat > "$ALIAS_FILE" <<EOF
# Auto-generated by $SCRIPT_DIR/install.sh on $NOW_ISO
# Re-run install.sh from any termpilot checkout to repoint termpilot there.
# Source: $SCRIPT_DIR
#
# Subcommands:
#   termpilot --help                       show usage
#   termpilot --set-relay-url URL          persist the relay URL
#   termpilot --get-relay-url              print the configured relay URL
#   termpilot --set-relay-secret SECRET   persist the relay Bearer token
#   termpilot --clear-relay-secret        forget the relay Bearer token
#   termpilot --generate-token             create or replace the encryption token
#   termpilot --show-token                 reveal the stored token (after password)
#   termpilot                              spawn \$SHELL through the wrapper
#   termpilot bash                         spawn bash explicitly
#   termpilot tmux new -A -s main          attach/create persistent tmux session
#   termpilot htop                         run any program in a PTY

termpilot() {
    if [[ ! -x "$WRAP_PATH" ]]; then
        echo "termpilot: $WRAP_PATH is missing or not executable — re-run install.sh" >&2
        return 1
    fi
    case "\${1:-}" in
        --help|-h|help|\\
        --generate-token|generate-token|\\
        --show-token|show-token|\\
        --set-relay-url|set-relay-url|\\
        --get-relay-url|get-relay-url|\\
        --set-relay-secret|set-relay-secret|\\
        --clear-relay-secret|clear-relay-secret|\\
        --version|version|-V|\\
        --update|update|\\
        --test-connection|test-connection)
            "$WRAP_PATH" "\$@"
            return
            ;;
    esac
    local tp_relay=""
    if [[ -r "$RELAY_URL_FILE" ]]; then
        tp_relay="\$(cat "$RELAY_URL_FILE")"
    fi
    if [[ -z "\$tp_relay" ]]; then
        echo "termpilot: relay URL not configured." >&2
        echo "  Run: termpilot --set-relay-url https://your.host/path" >&2
        return 2
    fi
    local tp_secret=""
    if [[ -r "$SECRET_FILE" ]]; then
        tp_secret="\$(cat "$SECRET_FILE")"
    fi
    # If the user passed no command, default to \$SHELL (fallback /bin/bash).
    # Wrapper flags (--force, --insecure, ...) are parsed by argparse from
    # anywhere in argv, so the user can mix them in freely.
    local default_shell="\${SHELL:-/bin/bash}"
    if [[ \$# -eq 0 ]]; then
        TERMPILOT_RELAY="\$tp_relay" TERMPILOT_SECRET="\$tp_secret" \\
            "$WRAP_PATH" run --title "\$(basename "\$PWD")" -- "\$default_shell"
    else
        TERMPILOT_RELAY="\$tp_relay" TERMPILOT_SECRET="\$tp_secret" \\
            "$WRAP_PATH" run --title "\$(basename "\$PWD")" "\$@"
    fi
}

# Short alias 'tp' — only defined if nothing else on this system already
# claims that name. Re-evaluated on every shell start, so installing a
# tool that provides 'tp' later (e.g. via apt) will silently disable
# this shortcut without you having to rerun install.sh.
if ! command -v tp >/dev/null 2>&1; then
    alias tp=termpilot
fi
EOF

# --- Idempotent source-block in shell rc files ---------------------------
# Pick rc files based on which shells the user actually uses. macOS users
# default to zsh (and login shells read ~/.bash_profile, not ~/.bashrc),
# so we cover all the common cases.

RC_FILES=()
case "${SHELL:-}" in
    */zsh)  RC_FILES+=("$HOME/.zshrc") ;;
    */bash) RC_FILES+=("$HOME/.bashrc") ;;
esac
# Also patch any rc files that already exist, even if they're not $SHELL
# — users often switch shells later or run termpilot from both.
for rc in "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.zshrc"; do
    if [[ -f "$rc" ]]; then
        already=0
        for x in "${RC_FILES[@]:-}"; do [[ "$x" == "$rc" ]] && already=1; done
        [[ $already -eq 0 ]] && RC_FILES+=("$rc")
    fi
done
# Fallback: if none of the above matched (fresh account, no rc files yet),
# create ~/.bashrc on Linux or ~/.zshrc on macOS so `termpilot` is at
# least defined somewhere.
if [[ ${#RC_FILES[@]} -eq 0 ]]; then
    case "$(uname -s 2>/dev/null)" in
        Darwin) RC_FILES+=("$HOME/.zshrc") ;;
        *)      RC_FILES+=("$HOME/.bashrc") ;;
    esac
fi

PATCHED_FILES=()
for rc in "${RC_FILES[@]}"; do
    touch "$rc"
    if grep -qF "$TAG_OPEN" "$rc"; then
        # Replace existing block in case the alias-file path ever changes.
        awk -v tag_open="$TAG_OPEN" -v tag_close="$TAG_CLOSE" -v alias_file="$ALIAS_FILE" '
            BEGIN { in_block = 0 }
            $0 == tag_open  { print tag_open; print "[ -f \"" alias_file "\" ] && source \"" alias_file "\""; print tag_close; in_block = 1; next }
            $0 == tag_close { in_block = 0; next }
            !in_block       { print }
        ' "$rc" > "$rc.tmp"
        mv "$rc.tmp" "$rc"
    else
        {
            printf '\n%s\n' "$TAG_OPEN"
            printf '[ -f "%s" ] && source "%s"\n' "$ALIAS_FILE" "$ALIAS_FILE"
            printf '%s\n' "$TAG_CLOSE"
        } >> "$rc"
    fi
    PATCHED_FILES+=("$rc")
done

# --- Report ---------------------------------------------------------------

echo "Installed."
echo "  function:     termpilot"
echo "  defined in:   $ALIAS_FILE"
echo "  binary:       $WRAP_PATH"
echo "  config dir:   $CONFIG_DIR"
echo "  rc files:     ${PATCHED_FILES[*]}"

# Report whether the 'tp' shortcut will activate on next shell start.
# The alias file does the real decision at runtime; this is just to
# inform the user up front.
if command -v tp >/dev/null 2>&1; then
    existing="$(type -p tp 2>/dev/null || true)"
    [[ -z "$existing" ]] && existing="$(type tp 2>&1 | head -1)"
    echo "  short alias:  tp NOT registered — '$existing' already claims that name"
else
    echo "  short alias:  tp  (also runs termpilot)"
fi
echo
echo "Activate now:  source ${PATCHED_FILES[0]}      (or open a new terminal)"
echo
echo "Next steps:"
if [[ ! -r "$RELAY_URL_FILE" ]]; then
    echo "  1. Tell termpilot where your relay lives:"
    echo "       termpilot --set-relay-url https://your.host/path"
fi
if [[ ! -r "$SECRET_FILE" ]]; then
    echo "  2. (Only if your relay sets RELAY_SECRET in config.php)"
    echo "       echo -n 'YOUR_RELAY_SECRET' > $SECRET_FILE && chmod 600 $SECRET_FILE"
fi
echo "  3. Generate your encryption token:"
echo "       termpilot --generate-token"
echo "  4. Paste the hex into the browser's manage-tokens dialog."
echo "  5. cd into a project and run:  termpilot"
